AWSTemplateFormatVersion: 2010-09-09
Resources:
  DNSManagerPolicy:
    Properties:
      Description: Allow the nodes to change route53 resources. Empowers both the external-dns and the cert-manager.
      ManagedPolicyName: demo-dns-manager
      PolicyDocument:
        Version: 2012-10-17
        Statement:
        - Effect: Allow
          Action: route53:GetChange
          Resource: arn:aws:route53:::change/*
        - Effect: Allow
          Action:
          - route53:ListHostedZones
          - route53:ListResourceRecordSets
          Resource:
          - "*"
        - Effect: Allow
          Action:
          - route53:ChangeResourceRecordSets
          # Change here to your ZONE_ID
          Resource: arn:aws:route53:::hostedzone/ZONE_ID
    Type: AWS::IAM::ManagedPolicy
