apiVersion: bootstrap.aws.infrastructure.cluster.x-k8s.io/v1beta1
kind: AWSIAMConfiguration
spec:
  bootstrapUser:
    enable: false
    userName: bootstrapper.cluster-api-provider-aws.sigs.k8s.io
  clusterAPIControllers:
    disable: false
  controlPlane:
    disable: false
    disableCloudProviderPolicy: false
    enableCSIPolicy: false
  eks:
    defaultControlPlaneRole:
      disable: false
    disable: false
    fargate:
      disable: true
    kmsAliasPrefix: cluster-api-provider-aws-*
    managedMachinePool:
      disable: true
  eventBridge: {}
  nameSuffix: .cluster-api-provider-aws.sigs.k8s.io
  nodes:
    disable: false
    disableCloudProviderPolicy: false
    ec2ContainerRegistryReadOnly: false
    extraPolicyAttachments:
    # CHANGE HERE TO YOUR ACCOUNT_ID
    - arn:aws:iam::ACCOUNT_ID:policy/demo-dns-manager
  partition: aws
  s3Buckets:
    enable: false
    namePrefix: cluster-api-provider-aws-
  secureSecretBackends:
  - secrets-manager
  stackName: cluster-api-provider-aws-sigs-k8s-io

