apiVersion: kommander.mesosphere.io/v1beta1
kind: VirtualGroup
metadata:
  name: admin
spec:
  subjects:
  - apiGroup: rbac.authorization.k8s.io
    kind: Group
    name: oidc:YOUR_GROUP
  # # If your setups does not support groups, you can add users to
  # # Kommander's virtual groups individually, just uncomment the lines
  # # below and change it to match your user's email.
  # - apiGroup: rbac.authorization.k8s.io
  #   kind: User
  #   name: youremail@yourcompany.com
---
apiVersion: workspaces.kommander.mesosphere.io/v1alpha1
kind: VirtualGroupKommanderClusterRoleBinding
metadata:
  name: role-binding-admin
spec:
  clusterRoleRef:
    name: cluster-admin
  virtualGroupRef:
    name: admin
